$('#stormBlanc').attr("title","Pas facile la vie de Stormtrooper");
$('#stormBlanc').attr("src","images/nouveauStorm.jpeg");
$('#stormBlanc').attr("alt","image de stormTrooper blanc");
$('#fontAChanger').attr("class","fas fa-fighter-jet");
$('.row4 h1').css("font-size","4rem");
$('.orange').css("opacity",".8");
$('.fondNoir').css("background-color","gray");
$('.fondBlanc').css("background-color","lightgray");
$('#storm').html("<h1>vive les Stormtroopers</h1>");
$('#père').html("<p> Père de Luke Skywalker</p>");
$('#cache').hide();
